version: '3.1'

services:
  flask:
    build:
      context: flask/
      dockerfile: ../docker/flask/Dockerfile

  db:
    image: mysql:latest
    volumes:
      - "./.docker_data/db:/var/lib/mysql"
    ports:
      - "33070:33060"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ~
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
